version: '3.8'

services:
  app:
    build: .
    container_name: task_manager_web-app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - db
    volumes:
      - ./app:/app
    networks:
      - taskmanager_network
    env_file:
      - .env 

  db:
    image: postgres:13
    container_name: task_manager_db
    environment:
      - POSTGRES_DB=task_manager_db
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - task_manager_db_data:/var/lib/postgresql/data
    networks:
      - taskmanager_network
    env_file:
      - .env 

networks:
  taskmanager_network:
    driver: bridge

volumes:
  task_manager_db_data: